### ISSUE TITLE
load autoloader in FunktionalTest/Frontend Bootstrap broken

### ISSUE THREAD

**Issue by sHorst** [TYPO3/testing-framework#144] opened 2019-07-28 20:03 UTC
Hey, 

in file Classes/Core/Functional/Framework/Frontend/RequestBootstrap.php on line 64 the framework try to load the composer autogenerated file. But this file is not on the same level as the index.php, but one folder up (as it should be out of the webroot) this means, the line should be corrected to

        `$directory = dirname(dirname(realpath($this->documentRoot . '/index.php')));`

The request object only gives this as error (path reduced for better readability)
  
>  [stderr] => PHP Warning:  require_once(.../.Build/Web/vendor/autoload.php): failed to open stream: No such file or directory in .../.Build/vendor/typo3/testing-framework/Classes/Core/Functional/Framework/Frontend/RequestBootstrap.php on line 64

Or did i setup my test setup wrong, i use the run_test.sh script and docker-compose.yml provided on the typo3 documentation.

**Comment by sHorst** [comment] 2019-07-29 09:43
Additional the Loading does not properly work when composer mode is on. So you should mark in the Documentation, that you need to set composer-mode to false in the composer.json of the extension.

```
	"extra": {
		"typo3/cms": {
...
			"composer-mode": false
		}
	}
```

**Comment by sven-carstens** [comment] 2019-08-05 07:18
Could you poste your whole composer.json setup?

For me the $directory from resolves to my PROJECT_DIR/.Build as intended and then finds its autoloader under PROJECT_DIR/.Build/vendor/autoload.php.

**Comment by maritwho** [comment] 2019-09-18 12:06
@sHorst Is there any update to this issue? I have the same problem and want to know, if there is a solution. thanks.

**Comment by bmack** [comment] 2019-11-28 21:47
Is this related to v4 or v5 branch?

**Comment by bmack** [comment] 2020-03-30 07:40
Just an update here: The testing framework is currently not working for composer mode, and no immediate plans are there to do so.

**Comment by bmack** [comment] 2020-03-30 07:40
(mostly due to time constraints)

**Comment by sHorst** [comment] 2020-03-30 07:43
can you add this to the documentation at least, will help a lot of people, who try to install it using composer :)

**Comment by alexander-nitsche** [comment] 2020-08-06 14:18
Hopefully with pull requests #189 and #190 the testing framework is working again with all scenarios of composer mode. At least my custom TYPO3 composer mode setup works fine with functional tests including frontend requests.

**Comment by alexander-nitsche** [comment] 2020-08-12 09:27
@sHorst , @sven-carstens : Can you confirm that your testing problems have gone with the latest testing-framework version 6.4.0?

**Comment by mkempe** [comment] 2020-12-30 16:45
@alexander-nitsche Thanks for your work, i can confirm that all problems are gone.

**Comment by lolli42** [comment] 2021-07-14 11:49
Thanks for feedback and works. Closing here.

**Closed by lolli42** 2021-07-14 11:49 UTC

**Comment by mkempe** [comment] 2021-07-14 12:45
@lolli42 Thanks for looking over. Can you please look at https://github.com/TYPO3/testing-framework/pull/223, it fixes the same problems but for TYPO3 9.x. I know, 9.x "is out the door", but it would help migrating extensions.

Thanks again.
