### ISSUE TITLE
Failed to load extensions without ext_emconf

### ISSUE THREAD

**Issue by Smove** [TYPO3/testing-framework#511] opened 2023-10-02 14:47 UTC
### What are you trying to achieve?
I want to test extensions without an ext_emconf.php file in composer mode.

### What do you get instead?
There is an exception thrown which states that dependencies are not installed even if they are. This problem exists with core extensions as the loaded packages are validated against the extension key, but check is performed with composer requirement. (typo3/cms-core is required, core is loaded).
`TYPO3\TestingFramework\Core\Exception: Package "<mypackage>" depends on package "typo3/cms-core" which does not exist.`

As soon as there is a ext_emconf which required only "typo3", this error is gone.

### How to reproduce the issue?

1. Delete ext_emconf.php from extension
2. Require "typo3/cms-core" in any version inside composer.json
3. Update composer
4. Run functional tests, error is thrown

### Specify some data of the environment

- TYPO3 testing framework version: 8.0.6
- TYPO3 version: 12.4.6
- TYPO3 installation type: composer
- PHP version: 8.1

**Comment by sbuerk** [comment] 2023-10-02 17:29
Closing this issue, as it's a duplicate of the already reported with #510.

**Closed by sbuerk** 2023-10-02 17:29 UTC
