### ISSUE TITLE
Support for ProphecyTrait in UnitTestCase

### ISSUE THREAD

**Issue by eliashaeussler** [TYPO3/testing-framework#178] opened 2020-04-22 16:42 UTC
With the [Deprecation of Prophecy integration within PHPUnit](https://github.com/sebastianbergmann/phpunit/issues/4141), it was recommended to use the [`ProphecyTrait` from `phpspec/prophecy-phpunit` package](https://github.com/phpspec/prophecy-phpunit/blob/master/src/ProphecyTrait.php) within PHPUnit tests.

## Problem

When using the trait together with a Unit test which extends the [`UnitTestCase`](https://github.com/TYPO3/testing-framework/blob/6.2.3/Classes/Core/Unit/UnitTestCase.php) class, the following exception occurs:

```
Error: Cannot access private property Vendor\Extension\Tests\Unit\MyTest::$prophet
```

## Reason

This is due to the fact that [properties are tried to unset during `tearDown()`](https://github.com/TYPO3/testing-framework/blob/6.2.3/Classes/Core/Unit/UnitTestCase.php#L142) which is not possible for private properties.
By now, this exception does not occur, because the [`$prophet` property is part of PHPUnit's `TestCase` class](https://github.com/sebastianbergmann/phpunit/blob/9.1.2/src/Framework/TestCase.php#L236). This makes the [preceding condition evaluating to `false`](https://github.com/TYPO3/testing-framework/blob/6.2.3/Classes/Core/Unit/UnitTestCase.php#L139).

When using the trait, the `$prophet` property is overridden and therefore the declaring class results to the concrete test class which in turn lets the condition evaluate to `true`.

## Expected behaviour

The property check in `tearDown()` should somehow ignore the traits' properties or unset them differently (if possible?).

**Comment by bmack** [comment] 2020-04-22 18:33
Hmm, yeah - I saw the deprecation. Do you have any good idea on how to achieve this?

**Comment by eliashaeussler** [comment] 2020-04-22 18:52
One idea I had was about using the magic `__unset` method in `UnitTestCase`. If a property cannot be unset, we can catch this and check if it's part of a trait. Something like this actually works for me:

```
public function __unset(string $name): void
{
    $reflection = new \ReflectionObject($this);
    $traits = $reflection->getTraits();

    foreach ($traits as $traitReflection) {
        if ($traitReflection->hasProperty($name)) {
            return;
        }
    }

    throw new \RuntimeException('Cannot unset property $' . $name . '.', 1587581149);
}
```

This would keep the [initial check](https://github.com/TYPO3/testing-framework/blob/6.2.3/Classes/Core/Unit/UnitTestCase.php#L142) clean and handles the exception only.

**Comment by DanielSiepmann** [comment] 2020-09-16 14:10
Wouldn't it make sense to check for the general issue? We already use the reflection on properties and could check if the property is private and skip them?
If something is private, it should be handled by the class / trait that adds it. Properties of `UnitTestCase` are skipped anyway, therefore no private property can be unset.

```diff
diff --git a/Classes/Core/Unit/UnitTestCase.php b/Classes/Core/Unit/UnitTestCase.php
index d8fd05d..ed48e0d 100644
--- a/Classes/Core/Unit/UnitTestCase.php
+++ b/Classes/Core/Unit/UnitTestCase.php
@@ -133,7 +133,8 @@ abstract class UnitTestCase extends BaseTestCase
         foreach ($reflection->getProperties() as $property) {
             $declaringClass = $property->getDeclaringClass()->getName();
             if (
-                !$property->isStatic()
+                !$property->isPrivate()
+                && !$property->isStatic()
                 && $declaringClass !== UnitTestCase::class
                 && $declaringClass !== BaseTestCase::class
                 && strpos($property->getDeclaringClass()->getName(), 'PHPUnit') !== 0
```

**Comment by ohader** [comment] 2020-10-06 13:13
A duplicate of `ProphecyTrait` has been introduced with #203

**Comment by DanielSiepmann** [comment] 2021-05-19 20:31
I don't get any issues with `6.8.2` and `PHPUnit 9.5.4` any more. Even when not using the provided duplicate of the Trait.

**Comment by bmack** [comment] 2021-08-05 19:14
Will close this issue now, looks like everything is OK now

**Closed by bmack** 2021-08-05 19:14 UTC
