### ISSUE TITLE
Functional tests: static data are only imported for first test

### ISSUE THREAD

**Issue by liayn** [TYPO3/testing-framework#397] opened 2022-08-10 16:54 UTC
### What are you trying to achieve?

Running multiple functional tests relying on static data from static_info_tables.

### What do you get instead?

Having static_country data available for each functional test.

### How to reproduce the issue?

Select anything from static_country in the first test, and do it again in the second.
Second one fails.

Swap the order of tests and experience the same behavior.

### Specify some data of the environment

- TYPO3 testing framework version: 6.16.
- TYPO3 version: 10
- TYPO3 installation type: composer
- PHP version: 7.4
- Web server used + version: -
- Operating system: -

**Comment by liayn** [comment] 2022-08-10 16:55
Static data are only imported for the first test run with `\TYPO3\TestingFramework\Core\Testbase::createDatabaseStructure`.
For all subsequent runs *all* tables are truncated, but static data are never reimported.

**Comment by oliverklee** [comment] 2022-08-10 17:13
Probably a duplicate of #377.

**Comment by sbuerk** [comment] 2022-08-10 17:55
yes, this is a duplicate. See recommendations in the comment here https://github.com/TYPO3/testing-framework/issues/377#issuecomment-1184278251

**Closed** 2022-08-10 18:20 UTC
