### ISSUE TITLE
BaseTestCase::tearDown wrongly assumes the error handler is always an instance of PHPUnit\Runner\ErrorHandler

### ISSUE THREAD

**Issue by unherz** [TYPO3/testing-framework#555] opened 2024-03-14 20:21 UTC
### What are you trying to achieve?
A simple running unit test, executed trough codeception

### What do you get instead?

An exception "tearDown() check: A dangling error handler has been found. Use restore_error_handler() to unset it.".  
Thrown by the BaseTestCase  in the error handler check
```
        $phpUnitUseErrorHandler = $this->shouldErrorHandlerBeUsed();
        if (($phpUnitUseErrorHandler && !$previousErrorHandler instanceof ErrorHandler)
            || (!$phpUnitUseErrorHandler && $previousErrorHandler !== null)
        ) {
            self::fail('tearDown() check: A dangling error handler has been found. Use restore_error_handler() to unset it.');
        }
```

### How to reproduce the issue?
1. Setup a TYPO3 environment 12.4.11 including the testing framework
2. setup codeception 5.1.2
3. Use the bootstrap file from typo3/testing-framework  (_Source/vendor/typo3/testing-framework/Resources/Core/Build/UnitTestsBootstrap.php_) as bootstrap file for codeception
4. Write a very stupid, simple test like this (for testing simply located in tests/unit): 
```php
<?php
declare(strict_types=1);

use TYPO3\TestingFramework\Core\Unit\UnitTestCase;

class EmptyUnitTest extends UnitTestCase
{

    protected function setUp(): void
    {
        parent::setUp();
    }

    protected function tearDown(): void
    {
        parent::tearDown();
    }

    public function testSimpleTestWillWork(): void
    {
        $this->assertEquals(1,1);
    }
}
```
5. Run codeception `./vendor/bin/codecept run unit`
6. The test will fail

### Additional information you would like to provide?

As a temporary fix you can simply overwrite the error handler and exception handler in the tearDown method like this:
```php
    protected function tearDown(): void
    {
        set_error_handler(new \PHPUnit\Runner\ErrorHandler());
        set_exception_handler(null);
        parent::tearDown();
    }
```

Codeception registers its own exception handler as well as its own error handler.  
It would be good it either the checks are less strict (bad idea) or if its somehow configurable to skip error handler and exception handler checks during tearDown on your own risk, so setups like this with codeception are still possible without unnecessary modifications to the valid unit test.

### Specify some data of the environment

- TYPO3 testing framework version: 12.4.11
- TYPO3 version: 12.4.11
- TYPO3 installation type: git + composer
- PHP version: 8.3.3
- Web server used + version:  apache 2.4.58
- Operating system: Alpine in a docker container

**Comment by sbuerk** [comment] 2024-03-14 20:48
Short answer:

The message exactly tells you that you have a dangling handler which (may) hide errors - even if it is the codeception. The check is implementend due to only direct phpunit support and will not be removed.

Long answer:

I said it already in the forge issue - if you want to use codeception for functional testing you have to build your own stack.

* UnitTestCase + UnitTestBootstrap-> pure unit test (without codeception - direct phpunit usage) 
* FunctionalTestCase + FunctionalTestBootstrap-> pure functional test (without codeception)

Acceptance testing based on codeception uses another approach, at least what the TYPO3 code uses AND what the supposed and supported way is.

You try to use something which is and will not be supporting the thing you will try to do, as they are literally incompatible.

TYPO3 core uses "Cest" and not "PHPUNIT" codeception testing - and that is the way officially supported, and providing a base bootstrap and tooling for that. "*TestCase" + "*TestBootstrap" are not part of that.

TYPO3 Core Codeception Acceptance Testing:

* https://github.com/TYPO3/typo3/tree/main/typo3/sysext/core/Tests/Acceptance
* https://github.com/TYPO3/typo3/blob/main/typo3/sysext/core/Tests/codeception.yml
* https://github.com/TYPO3/typo3/blob/main/typo3/sysext/core/Tests/parameters.yml

which extends from the testing-framework base form following folder

* https://github.com/TYPO3/testing-framework/tree/main/Classes/Core/Acceptance

TYPO3 Core uses `Build/Scripts/runTests.sh` to spawn the required container along with the apache2 container, a php-fpm container and before executing codeception - which builds a dedicated instance to be used for codeception testing.

FunctionalTestCase + FunctionalTestBootstrap is for functional tests WITHOUT codeception which builds currently for each functional testcase a dedicated instance and execute the testcase tests against that instance.

unit test does not bootstrap any TYPO3 related and are simple unit test - except that the UnitTestBootstrap at least initiazile some kind of class loading - but not DI and other stuff. Executed per default in the root folder structure if not configured away.

TYPO3 core decided to use only the acceptance part of codeception and not the rest. 

Ask your self - why should you use a 3rd party layer putting a lot of stuff on it and executing in the end phpunit.

If you want to use codeception for unit and functional testing YOU are required to build and maintain your own bootstrap on it. Or copy the UnitTestCase/FunctionalTestCase and other classes your own package and remove the parts you don't want to support.

Use the `UnitTestCase` as parent or your unit tests, and use the UnitTestBootstrap with the UnitTests.xml / FunctionalTests.xml and execute them directly with `phpunit`.

We will not remove the error/exception handler guard checks from the testingframework UnitTestCase/FunctionalTestCase (BaseTestCase) AS this hardens the testing and detects if a tests does not clean up a error/exception handler and than HIDING real issues or failing tests due to REAL issues (we had ~100 of hidden tests in the TYPO3 core). We also won't add a option for it to prevent that error slips into extensions or the core if someone make it to slipp the option enabled into the core.

If you use something ON top of it ... provide your own base test cases and not using the testing-framework chain.

Codeception BUILDS a huge layer on top of phpunit - which we lived for acceptance tests, but not fur unit and functional tests. 

I recommed that you use phpunit directly for unit and/or functional testing if you want to build upon this framework.

1. copy the unit configuration and bootstrap from the testing-framework resources folder to your project or extension to some folder + adjust the paths where to fund the unit or functional tests
2. require phpunit/phpunit to your project/extension as dev dependency
3. execute `vendor/bin/phpunit -c path/to/UnitTests.xml` to execute the unit tests

and similar for functional tests - except that that needs environment variables for the databse connection to use (you have to provide the correct database then like mariadb, mysql, postgres) - which is handled by the `Build/Scripts/runTests.sh` in the core, for example, for unit and functional tests.

Note: Codeception support will/may be dropped midterm due to working on removing it from the TYPO3 core and replaceing with something else.

> How to reproduce the issue?
Setup a TYPO3 environment 12.4.11 including the testing framework
setup codeception 5.1.2
Use the bootstrap file from typo3/testing-framework (Source/vendor/typo3/testing-framework/Resources/Core/Build/UnitTestsBootstrap.php) as bootstrap file for codeception
Write a very stupid, simple test like this (for testing simply located in tests/unit):

^^ nice that you tell the steps to reproduce - they are literlly wrong as it uses the raw phpunit based bootstrap towards unsupported. point.

Will close this as this is not bug - it's literlly trying to use a submarine to travel to the moon and wondering why it does not fly.

**Closed by sbuerk** 2024-03-14 20:48 UTC

**Comment by simonankele** [comment] 2024-03-15 11:09
So you really could have saved yourself that cheeky closing remark. Then you could have just as easily written "you idiot".
